# rename this file from "config.sample.yml" to "config.yml"

server:
  hostname: localhost
  port: 3150

security:
  jwtsigningkey: XXXXXX

database:
  user: XXXXXX
  password: XXXXXX
  hostname: 127.0.0.1
  port: 27017
  name: XXXXXX
  nopassword: false

cors:
  origins: []
  debug: false

mailing:
  accesskeyid: XXXXX
  secretaccesskey: XXXXX
  awsregion: eu-west-1
  enabletests: false
  debug: false
