# rename this file from "config.sample.yml" to "config.yml"

server:
  hostname: localhost
  port: 3150

security:
  jwtsigningkey: XXXXXX

database:
  user: XXXXXX
  password: XXXXXX
  hostname: localhost
  port: 27017
  name: XXXXXX
  nopassword: -

cors:
  origins: []
  debug: false
