# rename this file from "config.sample.yml" to "config.yml"

server:
  hostname: localhost
  port: 3150

security:
  jwtsigningkey: XXXXXX
  enablefaker: false

database:
  user: boomak_user
  password: XXXXXX
  hostname: localhost
  port: 27017
  name: boomak
  nopassword: true

cors:
  origins:
    - chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
    - http://127.0.0.1:3250
    - http://localhost:3250
  headers:
    - Content-Type
    - Authorization

mailing:
  accesskeyid: AKIAXXXXXX
  secretaccesskey: XXXXXX
  awsregion: eu-west-1
  fromemail: resurtm@gmail.com
  enabletestmailer: true
