# rename this file from "config.sample.yml" to "config.yml"

server:
  hostname: localhost
  port: 3150
  debug: true

security:
  jwtsigningkey: XXX

database:
  user: boomak_user
  password: 123123
  hostname: localhost
  port: 27017
  name: boomak
  nopassword: true

cors:
  origins:
    - chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
    - http://127.0.0.1:3250
    - http://localhost:3250
  headers:
    - Content-Type
    - Authorization
  debug: true

mailing:
  accesskeyid: XXX
  secretaccesskey: XXX
  awsregion: eu-west-1
  fromemail: resurtm@gmail.com
  enabletestmailer: true
  debug: true
